workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - test
  - build

test:
  stage: test
  tags: [docker]
  image: python:3.8-slim
  script:
    - pip install -r requirements/dev.txt
    - yapf -pqr .
    - pytest --cov=./ --cov-config=.coveragerc --junitxml=pytest-report.xml
  artifacts:
    when: always
    reports:
      junit: pytest-report.xml

build:
  stage: build
  tags: [docker]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.prod --destination $IMAGE_TAG
