workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - test
  - build

test:
  stage: test
  tags: [docker]
  image: python:3.8-slim
  script:
    - pip install -r requirements/dev.txt
    - yapf -pqr .
    - pytest --cov=./ --cov-config=.coveragerc --junitxml=pytest-report.xml
  artifacts:
    when: always
    reports:
      junit: pytest-report.xml

build:
  stage: build
  tags: [docker]
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
