name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: YAPF
      run: |
        pip install yapf
        yapf . -rd
